version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./src/public:/src/public
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./src/public:/src/public
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: 'mvc'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3307:3307
volumes:
  mysqldata: {}
